### ISSUE TITLE
calcSunRiseUTC vs calcSunriseUTC

### ISSUE THREAD

**Issue by drwison** [sely2k/SunSetRiseLib#3]
Hi,
is there a reason there is two functions to calculate sunrise? 
calcSunRiseUTC seems to return the correct results and is also used in the sample on the linked page:
http://pointofint.blogspot.it/2014/06/sunrise-and-sunset-in-c.html

It may be worthwhile to rename one it if it's legit or remove calcSunriseUTC.

Thanks for the lib!

Cheers
Will

**Comment by sely2k** [comment]
thankyou for the notification.
during the next week i'll try to fix the problem.
p.s. if you want you can download this lib from nuget
https://www.nuget.org/packages/SunSetRiseLib/

**Comment by sely2k** [comment]
hi the second function for caluculate the sunrise is for calculate the sunrise with a fraction of julian day... bissextile year and other...
this function don't work yet
I've renamed this function and deprecate it
tnk
